/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TreatmentsRouteImport } from './routes/treatments'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminTreatmentsRouteImport } from './routes/admin.treatments'
import { Route as AdminAssessmentsIndexRouteImport } from './routes/admin.assessments.index'
import { Route as AdminAssessmentsIdRouteImport } from './routes/admin.assessments.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsRoute = TreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTreatmentsRoute = AdminTreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssessmentsIndexRoute = AdminAssessmentsIndexRouteImport.update({
  id: '/assessments/',
  path: '/assessments/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssessmentsIdRoute = AdminAssessmentsIdRouteImport.update({
  id: '/assessments/$id',
  path: '/assessments/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/assessment': typeof AssessmentRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/testimonials': typeof TestimonialsRoute
  '/track': typeof TrackRoute
  '/treatments': typeof TreatmentsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/treatments': typeof AdminTreatmentsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/assessments/$id': typeof AdminAssessmentsIdRoute
  '/admin/assessments/': typeof AdminAssessmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/testimonials': typeof TestimonialsRoute
  '/track': typeof TrackRoute
  '/treatments': typeof TreatmentsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/treatments': typeof AdminTreatmentsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/assessments/$id': typeof AdminAssessmentsIdRoute
  '/admin/assessments': typeof AdminAssessmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/assessment': typeof AssessmentRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/testimonials': typeof TestimonialsRoute
  '/track': typeof TrackRoute
  '/treatments': typeof TreatmentsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/treatments': typeof AdminTreatmentsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/assessments/$id': typeof AdminAssessmentsIdRoute
  '/admin/assessments/': typeof AdminAssessmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/assessment'
    | '/contact'
    | '/gallery'
    | '/testimonials'
    | '/track'
    | '/treatments'
    | '/admin/enquiries'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/testimonials'
    | '/admin/treatments'
    | '/admin/'
    | '/admin/assessments/$id'
    | '/admin/assessments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assessment'
    | '/contact'
    | '/gallery'
    | '/testimonials'
    | '/track'
    | '/treatments'
    | '/admin/enquiries'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/testimonials'
    | '/admin/treatments'
    | '/admin'
    | '/admin/assessments/$id'
    | '/admin/assessments'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/assessment'
    | '/contact'
    | '/gallery'
    | '/testimonials'
    | '/track'
    | '/treatments'
    | '/admin/enquiries'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/testimonials'
    | '/admin/treatments'
    | '/admin/'
    | '/admin/assessments/$id'
    | '/admin/assessments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssessmentRoute: typeof AssessmentRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TrackRoute: typeof TrackRoute
  TreatmentsRoute: typeof TreatmentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments': {
      id: '/treatments'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof TreatmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/treatments': {
      id: '/admin/treatments'
      path: '/treatments'
      fullPath: '/admin/treatments'
      preLoaderRoute: typeof AdminTreatmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assessments/': {
      id: '/admin/assessments/'
      path: '/assessments'
      fullPath: '/admin/assessments/'
      preLoaderRoute: typeof AdminAssessmentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assessments/$id': {
      id: '/admin/assessments/$id'
      path: '/assessments/$id'
      fullPath: '/admin/assessments/$id'
      preLoaderRoute: typeof AdminAssessmentsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminTreatmentsRoute: typeof AdminTreatmentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAssessmentsIdRoute: typeof AdminAssessmentsIdRoute
  AdminAssessmentsIndexRoute: typeof AdminAssessmentsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminTreatmentsRoute: AdminTreatmentsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAssessmentsIdRoute: AdminAssessmentsIdRoute,
  AdminAssessmentsIndexRoute: AdminAssessmentsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AssessmentRoute: AssessmentRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  TestimonialsRoute: TestimonialsRoute,
  TrackRoute: TrackRoute,
  TreatmentsRoute: TreatmentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
